### ISSUE TITLE
Not adjusting top scrollbar when child resizes

### ISSUE THREAD

**Issue by kasbah** [umchee/react-double-scrollbar#5]
Hey, thanks for the DoubleScrollbar, I have been using it quite a lot on my site: https://kitnic.it

I am just developing a sort of spreadsheet editor using it and I noticed the top scrollbar isn't adjusting every time the content is adjusted. 

[Here](http://cloud.monostable.co.uk/double-scrollbar/) is what I am working on. You can expand the table by presssing the `more ...` button and collapse it again by pressing the `<-- less` button and you will see the top bar doesn't go down again. [Here](https://github.com/kasbah/bom-builder/blob/10dc611ac44d0196e433269679c95325c58189b2/src/App.js#L16) is the source-code.

**Comment by umchee** [comment]
Hello, good to hear the scrollbar is useful for you. I started looking into your issue. Currently the scrollbar only recalculates the width of the div of the top scrollbar on a window.resize event.  In your case the width of the content is changing, not the size of the window. 

Thanks for providing sample code, it makes it easier to see what is happening.  From the code you provided the parent of DoubleScrollbar  is re-rendering when the more or less button is clicked and I see this is causing the re-render of the DoubleScrollbar but it is using the old width value of the children wrapper.

I am testing a fix and will let you know when it is ready.

**Comment by umchee** [comment]
Issue resolved in v0.0.15

**Comment by kasbah** [comment]
Hey, thanks again for fixing this. I recently updated the version deployed to kitspace.org (the renamed kitnic.it) and was able to add a "View All" button and it resizes perfectly when lines are added/removed from the table within it. For example [on this page](https://kitspace.org/boards/github.com/kitspace-forks/bq25570_harvester/).

**Comment by umchee** [comment]
Nice looking site.  Thanks for the feedback, glad to hear the fix is working for you.
